-- Insert students data from the attendance reports
INSERT INTO users (id, full_name, email, role, department, mobile, created_at, updated_at) VALUES
-- First batch of students
(gen_random_uuid(), 'BAILAPUDI MRUDULA', 'bailapudi.mrudula@student.edu', 'student', 'computer science', '9876543210', now(), now()),
(gen_random_uuid(), 'A RAJ KUMAR', 'a.rajkumar@student.edu', 'student', 'computer science', '9876543211', now(), now()),
(gen_random_uuid(), 'EDUPUGANTI AKASH KUMAR', 'edupuganti.akash@student.edu', 'student', 'computer science', '9876543212', now(), now()),
(gen_random_uuid(), 'KONA SAI THARUN', 'kona.saitharun@student.edu', 'student', 'computer science', '9876543213', now(), now()),
(gen_random_uuid(), 'KINTALI SIVA HARSHIKA', 'kintali.harshika@student.edu', 'student', 'computer science', '9876543214', now(), now()),
(gen_random_uuid(), 'UPPUGANTI AMRUTHA RATNA VALLI', 'uppuganti.amrutha@student.edu', 'student', 'computer science', '9876543215', now(), now()),
(gen_random_uuid(), 'PONNAGANTI OM SRI RAM', 'ponnaganti.om@student.edu', 'student', 'computer science', '9876543216', now(), now()),
(gen_random_uuid(), 'MEDAPATI DURGASAIDILEEPSATYANARAYANA REDDY', 'medapati.durga@student.edu', 'student', 'computer science', '9876543217', now(), now()),
(gen_random_uuid(), 'AASHITA JOLLY', 'aashita.jolly@student.edu', 'student', 'computer science', '9876543218', now(), now()),
(gen_random_uuid(), 'NAMBURI AJAY KUMAR', 'namburi.ajay@student.edu', 'student', 'computer science', '9876543219', now(), now()),
(gen_random_uuid(), 'MANTRI VENKAT SUNDAR SAMPAT CHATHUR VEDA', 'mantri.venkat@student.edu', 'student', 'computer science', '9876543220', now(), now()),
(gen_random_uuid(), 'ANNAM POSHAK', 'annam.poshak@student.edu', 'student', 'computer science', '9876543221', now(), now()),
(gen_random_uuid(), 'GETTINENI NATANYA', 'gettineni.natanya@student.edu', 'student', 'computer science', '9876543222', now(), now()),
(gen_random_uuid(), 'RAPARTY HEMANTH KUMAR', 'raparty.hemanth@student.edu', 'student', 'computer science', '9876543223', now(), now()),
(gen_random_uuid(), 'SADI ROSHAN', 'sadi.roshan@student.edu', 'student', 'computer science', '9876543224', now(), now()),
(gen_random_uuid(), 'PAMPANA VENKATA BHAVANA MEENAKSHI', 'pampana.bhavana@student.edu', 'student', 'computer science', '9876543225', now(), now()),
(gen_random_uuid(), 'KOTAGIRI CHARISHMA', 'kotagiri.charishma@student.edu', 'student', 'computer science', '9876543226', now(), now()),
(gen_random_uuid(), 'VYSYARAJU UTTAM RAJU', 'vysyaraju.uttam@student.edu', 'student', 'computer science', '9876543227', now(), now()),
(gen_random_uuid(), 'PAILA ABHINAV', 'paila.abhinav@student.edu', 'student', 'computer science', '9876543228', now(), now()),
(gen_random_uuid(), 'KANCHARANA NIRMAL SAI', 'kancharana.nirmal@student.edu', 'student', 'computer science', '9876543229', now(), now()),
(gen_random_uuid(), 'ANUPOJU SUSMITHA', 'anupoju.susmitha@student.edu', 'student', 'computer science', '9876543230', now(), now()),
(gen_random_uuid(), 'SARAGADA JOSH', 'saragada.josh@student.edu', 'student', 'computer science', '9876543231', now(), now()),
(gen_random_uuid(), 'HARSH VARDHEN GOLAGANI', 'harsh.golagani@student.edu', 'student', 'computer science', '9876543232', now(), now()),
(gen_random_uuid(), 'PEDIREDLA SAI LOKESH', 'pediredla.lokesh@student.edu', 'student', 'computer science', '9876543233', now(), now()),
-- Second batch
(gen_random_uuid(), 'GARAPATI HIMANI', 'garapati.himani@student.edu', 'student', 'computer science', '9876543234', now(), now()),
(gen_random_uuid(), 'KARRI LAKSHMI BHOOMIKA', 'karri.lakshmi@student.edu', 'student', 'computer science', '9876543235', now(), now()),
(gen_random_uuid(), 'PATCHIGOLLA SAI NIKHITA', 'patchigolla.nikhita@student.edu', 'student', 'computer science', '9876543236', now(), now()),
(gen_random_uuid(), 'NALLURI KAVYA SRI', 'nalluri.kavya@student.edu', 'student', 'computer science', '9876543237', now(), now()),
(gen_random_uuid(), 'LAKSHMI MANMAYEE ADARI', 'lakshmi.adari@student.edu', 'student', 'computer science', '9876543238', now(), now()),
(gen_random_uuid(), 'VENISHA A', 'venisha.a@student.edu', 'student', 'computer science', '9876543239', now(), now()),
(gen_random_uuid(), 'KALISETTI CHANDU', 'kalisetti.chandu@student.edu', 'student', 'computer science', '9876543240', now(), now()),
(gen_random_uuid(), 'TEJASWINI KOTHARU', 'tejaswini.kotharu@student.edu', 'student', 'computer science', '9876543241', now(), now()),
(gen_random_uuid(), 'NIKHITA KUNISETTI', 'nikhita.kunisetti@student.edu', 'student', 'computer science', '9876543242', now(), now()),
(gen_random_uuid(), 'POTHINA GUNA DEEPTHI', 'pothina.deepthi@student.edu', 'student', 'computer science', '9876543243', now(), now()),
(gen_random_uuid(), 'MOVVA HEMA HARSHA VIRAN', 'movva.hema@student.edu', 'student', 'computer science', '9876543244', now(), now()),
(gen_random_uuid(), 'NOWBATHULA JAYA PRAKASH', 'nowbathula.jaya@student.edu', 'student', 'computer science', '9876543245', now(), now()),
(gen_random_uuid(), 'KARRI THRAITHA', 'karri.thraitha@student.edu', 'student', 'computer science', '9876543246', now(), now()),
(gen_random_uuid(), 'THONDAPU MAANYASREE REDDY', 'thondapu.maanya@student.edu', 'student', 'computer science', '9876543247', now(), now()),
(gen_random_uuid(), 'NADIMPALLI SAI SATHWIKA', 'nadimpalli.sathwika@student.edu', 'student', 'computer science', '9876543248', now(), now()),
(gen_random_uuid(), 'EEGAM SRIKAR', 'eegam.srikar@student.edu', 'student', 'computer science', '9876543249', now(), now()),
(gen_random_uuid(), 'ANNAM PRAMOD MANOHAR', 'annam.pramod@student.edu', 'student', 'computer science', '9876543250', now(), now()),
(gen_random_uuid(), 'BOGI CHAKRADHAR', 'bogi.chakradhar@student.edu', 'student', 'computer science', '9876543251', now(), now()),
(gen_random_uuid(), 'ADAPA BHARGAVA VENKATA SAI', 'adapa.bhargava@student.edu', 'student', 'computer science', '9876543252', now(), now()),
(gen_random_uuid(), 'VATTIKOLLA CHAITANYA', 'vattikolla.chaitanya@student.edu', 'student', 'computer science', '9876543253', now(), now()),
(gen_random_uuid(), 'BUKKANI PUSHPA SRI RAM', 'bukkani.pushpa@student.edu', 'student', 'computer science', '9876543254', now(), now()),
(gen_random_uuid(), 'DUMPA SRIVATSA KARTHIKEEYA REDDY', 'dumpa.srivatsa@student.edu', 'student', 'computer science', '9876543255', now(), now()),
(gen_random_uuid(), 'DALLI SAGAR DURGA PRADEEP', 'dalli.sagar@student.edu', 'student', 'computer science', '9876543256', now(), now()),
(gen_random_uuid(), 'DWARAPU MONISHA', 'dwarapu.monisha@student.edu', 'student', 'computer science', '9876543257', now(), now()),
(gen_random_uuid(), 'ANGARA VENKATA SESHANK SHYAM', 'angara.seshank@student.edu', 'student', 'computer science', '9876543258', now(), now()),
(gen_random_uuid(), 'MARIYADALA SURYA VENKATA SAI JOSHNA MANI', 'mariyadala.surya@student.edu', 'student', 'computer science', '9876543259', now(), now()),
-- Third batch
(gen_random_uuid(), 'J TANUJ', 'j.tanuj@student.edu', 'student', 'computer science', '9876543260', now(), now()),
(gen_random_uuid(), 'GULLAPALLI YUKTHA', 'gullapalli.yuktha@student.edu', 'student', 'computer science', '9876543261', now(), now()),
(gen_random_uuid(), 'ADDALA AKSHITH', 'addala.akshith@student.edu', 'student', 'computer science', '9876543262', now(), now()),
(gen_random_uuid(), 'PASUPULETI BHAVYASREE', 'pasupuleti.bhavya@student.edu', 'student', 'computer science', '9876543263', now(), now()),
(gen_random_uuid(), 'HARIKA GANNAMANEDI', 'harika.gannamanedi@student.edu', 'student', 'computer science', '9876543264', now(), now()),
(gen_random_uuid(), 'SATVIK KANNEGANTI', 'satvik.kanneganti@student.edu', 'student', 'computer science', '9876543265', now(), now()),
(gen_random_uuid(), 'POTNURU JOSHIKA', 'potnuru.joshika@student.edu', 'student', 'computer science', '9876543266', now(), now()),
(gen_random_uuid(), 'LANKA LAKSHMI POOJITHA', 'lanka.poojitha@student.edu', 'student', 'computer science', '9876543267', now(), now()),
(gen_random_uuid(), 'MANTHENA ASHRITHA', 'manthena.ashritha@student.edu', 'student', 'computer science', '9876543268', now(), now()),
(gen_random_uuid(), 'KOTA MAHESH BABU', 'kota.mahesh@student.edu', 'student', 'computer science', '9876543269', now(), now()),
(gen_random_uuid(), 'NAKKILA SAVISH SIDDHARTH', 'nakkila.savish@student.edu', 'student', 'computer science', '9876543270', now(), now()),
(gen_random_uuid(), 'SUTHAPALLI HARSHITHA', 'suthapalli.harshitha@student.edu', 'student', 'computer science', '9876543271', now(), now()),
(gen_random_uuid(), 'PONNADA SURAJ SUNDAR DEEPANSH', 'ponnada.suraj@student.edu', 'student', 'computer science', '9876543272', now(), now()),
(gen_random_uuid(), 'SHAIK NOUSHAD AHMED', 'shaik.noushad@student.edu', 'student', 'computer science', '9876543273', now(), now()),
(gen_random_uuid(), 'GUNDETI SHREYAS REDDY', 'gundeti.shreyas@student.edu', 'student', 'computer science', '9876543274', now(), now()),
(gen_random_uuid(), 'SACHIN AGARWAL', 'sachin.agarwal@student.edu', 'student', 'computer science', '9876543275', now(), now());

-- Insert faculty members
INSERT INTO users (id, full_name, email, role, department, mobile, created_at, updated_at) VALUES
(gen_random_uuid(), 'Dr. T Srikanth', 'dr.srikanth@faculty.edu', 'faculty', 'computer science', '9876540001', now(), now()),
(gen_random_uuid(), 'Dr. Ravi Teja Gedela', 'dr.raviteja@faculty.edu', 'faculty', 'computer science', '9876540002', now(), now()),
(gen_random_uuid(), 'Dr. Amanapu Yaswanth', 'dr.amanapu@faculty.edu', 'faculty', 'computer science', '9876540003', now(), now()),
(gen_random_uuid(), 'Dr. Manda Rama Narasinga Rao', 'dr.manda@faculty.edu', 'faculty', 'computer science', '9876540004', now(), now()),
(gen_random_uuid(), 'Mr. Dr.Maddamsetty Ramesh', 'mr.maddamsetty@faculty.edu', 'faculty', 'computer science', '9876540005', now(), now()),
(gen_random_uuid(), 'Dr. Sreekanth Puli', 'dr.sreekanth@faculty.edu', 'faculty', 'computer science', '9876540006', now(), now()),
(gen_random_uuid(), 'Dalli Sagar Durga Pradeep', 'dalli.sagar.faculty@faculty.edu', 'faculty', 'computer science', '9876540007', now(), now());
